<a href="https://colab.research.google.com/github/ElsieOtube/Machine-Learning-/blob/main/task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LassoCV
import io
import csv
from google.colab import files

In [4]:
upload = files.upload()
data = pd.read_csv(io.BytesIO(upload['modified_data.csv']))

Saving modified_data.csv to modified_data (1).csv


In [15]:
data.head(10)

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0          60       RL         65.0     8450   Pave      Reg         Lvl   
1          20       RL         80.0     9600   Pave      Reg         Lvl   
2          60       RL         68.0    11250   Pave      IR1         Lvl   
3          70       RL         60.0     9550   Pave      IR1         Lvl   
4          60       RL         84.0    14260   Pave      IR1         Lvl   
5          50       RL         85.0    14115   Pave      IR1         Lvl   
6          20       RL         75.0    10084   Pave      Reg         Lvl   
7          60       RL          NaN    10382   Pave      IR1         Lvl   
8          50       RM         51.0     6120   Pave      Reg         Lvl   
9         190       RL         50.0     7420   Pave      Reg         Lvl   

  Utilities LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch  \
0    AllPub    Inside       Gtl  ...             0         0           0   
1    AllPub       FR2       Gtl  ...             0         0           0   
2    AllPub    Inside       Gtl  ...             0         0           0   
3    AllPub    Corner       Gtl  ...           272         0           0   
4    AllPub       FR2       Gtl  ...             0         0           0   
5    AllPub    Inside       Gtl  ...             0       320           0   
6    AllPub    Inside       Gtl  ...             0         0           0   
7    AllPub    Corner       Gtl  ...           228         0           0   
8    AllPub    Inside       Gtl  ...           205         0           0   
9    AllPub    Corner       Gtl  ...             0         0           0   

  PoolArea MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
0        0       0       2    2008        WD         Normal    208500  
1        0       0       5    2007        WD         Normal    181500  
2        0       0       9    2008        WD         Normal    223500  
3        0       0       2    2006        WD        Abnorml    140000  
4        0       0      12    2008        WD         Normal    250000  
5        0     700      10    2009        WD         Normal    143000  
6        0       0       8    2007        WD         Normal    307000  
7        0     350      11    2009        WD         Normal    200000  
8        0       0       4    2008        WD        Abnorml    129900  
9        0       0       1    2008        WD         Normal    118000  

[10 rows x 76 columns]

In [5]:
data.shape

(1460, 77)

In [6]:
data.drop('Id',inplace=True,axis=1)

In [7]:
data.head(5)

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0          60       RL         65.0     8450   Pave      Reg         Lvl   
1          20       RL         80.0     9600   Pave      Reg         Lvl   
2          60       RL         68.0    11250   Pave      IR1         Lvl   
3          70       RL         60.0     9550   Pave      IR1         Lvl   
4          60       RL         84.0    14260   Pave      IR1         Lvl   

  Utilities LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch  \
0    AllPub    Inside       Gtl  ...             0         0           0   
1    AllPub       FR2       Gtl  ...             0         0           0   
2    AllPub    Inside       Gtl  ...             0         0           0   
3    AllPub    Corner       Gtl  ...           272         0           0   
4    AllPub       FR2       Gtl  ...             0         0           0   

  PoolArea MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
0        0       0       2    2008        WD         Normal    208500  
1        0       0       5    2007        WD         Normal    181500  
2        0       0       9    2008        WD         Normal    223500  
3        0       0       2    2006        WD        Abnorml    140000  
4        0       0      12    2008        WD         Normal    250000  

[5 rows x 76 columns]

In [8]:
original_features=list(data.columns)
len(original_features)

76

In [9]:
features_missing_values=list(data.columns[data.isna().any()])
len(features_missing_values)

15

In [10]:
len(data)

1460

In [11]:
bfill,mean_fill=[],[]

In [12]:
for feature in features_missing_values:
  print(feature,' ',data[feature].isna().sum()/len(data)*100,' ',data[feature].dtype)
  if data[feature].dtype=='float64':
    mean_fill.append(feature)
  else:
    bfill.append(feature)

LotFrontage   17.73972602739726   float64
MasVnrType   0.547945205479452   object
MasVnrArea   0.547945205479452   float64
BsmtQual   2.5342465753424657   object
BsmtCond   2.5342465753424657   object
BsmtExposure   2.6027397260273974   object
BsmtFinType1   2.5342465753424657   object
BsmtFinType2   2.6027397260273974   object
Electrical   0.0684931506849315   object
FireplaceQu   47.26027397260274   object
GarageType   5.5479452054794525   object
GarageYrBlt   5.5479452054794525   float64
GarageFinish   5.5479452054794525   object
GarageQual   5.5479452054794525   object
GarageCond   5.5479452054794525   object


In [13]:
bfill

['MasVnrType',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond']

In [16]:
mean_fill

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']

In [17]:
for feature in mean_fill:
  data[feature].fillna(data[feature].mean(),inplace=True)

In [18]:
for feature in bfill:
  data[feature].fillna(method='bfill',inplace=True)

In [19]:
data.columns[data.isna().any()]

Index(['FireplaceQu'], dtype='object')

In [21]:
data['GarageCond'].isna().sum()

0

In [22]:
data['MasVnrArea'].isna().sum()

0

In [23]:
data['GarageCond'].fillna(method='ffill',inplace=True)

In [24]:
categorical_features=list(data.select_dtypes(include=['object']).columns)
categorical_features

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

In [25]:
numerical=list(set(original_features)-set(categorical_features))
numerical

['2ndFlrSF',
 'MoSold',
 'OverallQual',
 'KitchenAbvGr',
 'GarageArea',
 'MiscVal',
 'PoolArea',
 'BedroomAbvGr',
 'BsmtFullBath',
 'LotFrontage',
 'WoodDeckSF',
 'OpenPorchSF',
 'Fireplaces',
 'GrLivArea',
 'HalfBath',
 'TotRmsAbvGrd',
 'LotArea',
 'FullBath',
 '3SsnPorch',
 'YearBuilt',
 'YearRemodAdd',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'YrSold',
 'LowQualFinSF',
 'MasVnrArea',
 'BsmtUnfSF',
 'OverallCond',
 'TotalBsmtSF',
 'GarageCars',
 'SalePrice',
 'ScreenPorch',
 'MSSubClass',
 'BsmtHalfBath',
 '1stFlrSF',
 'EnclosedPorch',
 'GarageYrBlt']

In [26]:
nominal=['MSZoning','LandContour','Neighborhood']
ordinal=list(set(categorical_features)-set(nominal))

In [27]:
target=['SalePrice']

In [28]:
df_nominal=pd.get_dummies(data[nominal])

In [29]:
for feature in ordinal:
  data[feature]=data[feature].astype('category').cat.codes

df_ordinal=data[ordinal]

In [30]:
data[numerical]

2ndFlrSF  MoSold  OverallQual  KitchenAbvGr  GarageArea  MiscVal  \
0          854       2            7             1         548        0   
1            0       5            6             1         460        0   
2          866       9            7             1         608        0   
3          756       2            7             1         642        0   
4         1053      12            8             1         836        0   
...        ...     ...          ...           ...         ...      ...   
1455       694       8            6             1         460        0   
1456         0       2            6             1         500        0   
1457      1152       5            7             1         252     2500   
1458         0       4            5             1         240        0   
1459         0       6            5             1         276        0   

      PoolArea  BedroomAbvGr  BsmtFullBath  LotFrontage  ...  OverallCond  \
0            0             3             1         65.0  ...            5   
1            0             3             0         80.0  ...            8   
2            0             3             1         68.0  ...            5   
3            0             3             1         60.0  ...            5   
4            0             4             1         84.0  ...            5   
...        ...           ...           ...          ...  ...          ...   
1455         0             3             0         62.0  ...            5   
1456         0             3             1         85.0  ...            6   
1457         0             4             0         66.0  ...            9   
1458         0             2             1         68.0  ...            6   
1459         0             3             1         75.0  ...            6   

      TotalBsmtSF  GarageCars  SalePrice  ScreenPorch  MSSubClass  \
0             856           2     208500            0          60   
1            1262           2     181500            0          20   
2             920           2     223500            0          60   
3             756           3     140000            0          70   
4            1145           3     250000            0          60   
...           ...         ...        ...          ...         ...   
1455          953           2     175000            0          60   
1456         1542           2     210000            0          20   
1457         1152           1     266500            0          70   
1458         1078           1     142125            0          20   
1459         1256           1     147500            0          20   

      BsmtHalfBath  1stFlrSF  EnclosedPorch  GarageYrBlt  
0                0       856              0       2003.0  
1                1      1262              0       1976.0  
2                0       920              0       2001.0  
3                0       961            272       1998.0  
4                0      1145              0       2000.0  
...            ...       ...            ...          ...  
1455             0       953              0       1999.0  
1456             0      2073              0       1978.0  
1457             0      1188              0       1941.0  
1458             0      1078            112       1950.0  
1459             0      1256              0       1965.0  

[1460 rows x 37 columns]

In [31]:
new_data=pd.concat([df_nominal,df_ordinal,data[numerical]],axis=1)

In [32]:
new_data.shape

(1460, 107)

In [33]:
new_data.drop('SalePrice',axis=1,inplace=True)

In [34]:
X= new_data.to_numpy()

In [35]:
X[0]

array([0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 3.000e+00,
       4.000e+00, 0.000e+00, 6.000e+00, 4.000e+00, 2.000e+00, 1.000e+00,
       4.000e+00, 3.000e+00, 8.000e+00, 2.000e+00, 0.000e+00, 2.000e+00,
       2.000e+00, 4.000e+00, 1.200e+01, 4.000e+00, 1.000e+00, 5.000e+00,
       4.000e+00, 1.000e+00, 2.000e+00, 3.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 2.000e+00, 2.000e+00, 1.000e+00, 0.000e+00, 2.000e+00,
       0.000e+00, 4.000e+00, 1.300e+01, 5.000e+00, 8.540e+02, 2.000e+00,
       7.000e+00, 1.000e+00, 5.480e+02, 0.000e+00, 0.000e+00, 3.000e+00,
       1.000e+00, 6.500e+01, 0.000e+00, 6.100e+01, 

In [36]:
X=StandardScaler().fit_transform(X)

In [38]:
X[0]

array([-0.08304548, -0.21585871, -0.10526316,  0.51813339, -0.41895507,
       -0.21235968, -0.18831089, -0.15899968,  0.33712564, -0.10854037,
       -0.03703704, -0.10526316, -0.20339487, -0.1398323 ,  2.95522137,
       -0.19025216, -0.27116307, -0.23917551, -0.16124951, -0.10854037,
       -0.1863522 , -0.42683279, -0.07875671, -0.22941573, -0.16998114,
       -0.23595776, -0.28963792, -0.13199092, -0.23106504, -0.20521398,
       -0.25018188, -0.13199092, -0.16347148, -0.08712888, -0.23012211,
        0.64046232,  0.2085023 , -0.02618016,  0.25597761,  0.22403433,
       -0.29055229, -0.49151573,  0.60466978,  0.28780036,  0.31386709,
       -0.03628912, -0.22571613, -0.40779461, -0.40936914,  0.36420746,
        0.74309239,  0.18797343, -0.12579688,  0.30941909,  1.11571093,
       -0.12304604,  0.83559903,  0.75073056,  0.26381257,  0.06423821,
       -1.23804229, -0.03174026, -0.77797579, -0.71775144, -0.41169079,
        0.28974476, -0.88465767,  0.303692  ,  0.75162623,  1.02

In [39]:
y=data[target]

In [40]:
y=y.to_numpy()

In [41]:
y.shape

(1460, 1)

In [42]:
y

array([[208500],
       [181500],
       [223500],
       ...,
       [266500],
       [142125],
       [147500]])

In [43]:
y=StandardScaler().fit_transform(y)

In [44]:
y

array([[ 0.34727322],
       [ 0.00728832],
       [ 0.53615372],
       ...,
       [ 1.07761115],
       [-0.48852299],
       [-0.42084081]])

In [45]:
X.shape

(1460, 106)

In [46]:
X

array([[-0.08304548, -0.21585871, -0.10526316, ..., -0.79343379,
        -0.3593249 ,  1.02115667],
       [-0.08304548, -0.21585871, -0.10526316, ...,  0.25714043,
        -0.3593249 , -0.10448286],
       [-0.08304548, -0.21585871, -0.10526316, ..., -0.62782603,
        -0.3593249 ,  0.93777596],
       ...,
       [-0.08304548, -0.21585871, -0.10526316, ...,  0.06565646,
        -0.3593249 , -1.56364521],
       [-0.08304548, -0.21585871, -0.10526316, ..., -0.21898188,
         1.47378925, -1.18843203],
       [-0.08304548, -0.21585871, -0.10526316, ...,  0.2416147 ,
        -0.3593249 , -0.56307674]])

In [47]:
pca=PCA(n_components=2)

In [48]:
p_components=pca.fit_transform(X)

In [49]:
p_components

array([[ 2.44422859, -1.28395423],
       [ 0.31735517,  2.63309824],
       [ 2.85812755, -0.81621162],
       ...,
       [ 1.26129288, -0.85736958],
       [-2.82789095,  3.27211142],
       [-0.75425977,  2.76655823]])

In [50]:
pca.explained_variance_ratio_

array([0.10560106, 0.04471871])

In [51]:
reg=LassoCV()

In [52]:
reg.fit(p_components,y)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:1571: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LassoCV()

In [53]:
reg.coef_

array([0.25387432, 0.0190224 ])